name: CI-CD (Demo)

on: push

jobs:
  deploy:
    name: Complete CI-CD Job
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Create a temporary artifact downloads folder
        run: mkdir downloads
   
      - name: Choosing Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.0.app
        
      - name: Xcode version 
        run: /usr/bin/xcodebuild -version
        
      - name: Build Clean
        run: |
          echo "Your Build Folder is Cleaning"
          xcodebuild clean -project TestingCi.xcodeproj -scheme TestingCi | xcpretty
          
      - name: Build Test
        run: |
          echo "Your Build is Testing"
#          xcodebuild test -project TestingCi.xcodeproj -scheme TestingCi -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty -s
      
      - name: Install gpg
        run: brew install gnupg
        
      - name: Setup Provisioning Profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: chmod 755 ./.github/secrets/decrypt_secrets.sh
        
      - name: Archiving project
#        env:
#          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: chmod 755 ./.github/scripts/archive_app.sh
      
      - name: Exporting .ipa
        run: chmod 755 ./.github/scripts/export_app.sh
        
      - name: Publishing App
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: xcrun altool --upload-app -t ios -f $PWD/build/ -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose

